language: node_js
node_js:
- '0.11'
- '0.10'
- '0.8'
- '0.6'
env:
  - secure: gm+WFqzl3cXRxEvKp/T7Oo7XgEBRrcjRP/7V20x7KR3/5K8a0gz6r1ZLLUAFXvh3Lr2Ha1ldfLfCzbffEhc8B92QW+c3WODeJFXTutbLBCf/1mOPbs3NpzLOBRxS1ViU2ceABysjcfwBo5PsCBWtLDu8ZB2cycqSBvK3cJeRd+w= ZEijN5j6lQGvIrX5DnaXywPE52OFaHL64z2OAPtg3Qr9O+yI5TSjFzDb+MxFLCAXOcIs2+yxrIXR6SY7pVmZXnQonL9Bpawo/KHtMn+WivLU/Qo5YBUjYRjcdWzMk3mLy9uHB6FrODm6iPoc0HGRFvQPbf7PHlZHAvaXLcE0RZY= QrmFjTs3biizoTcSz2ZBsmWX0Y9VDx6W7LhcnHQJHNu2E3AWeR5GZUcYrfflX2P0y1WgSS6t9/tSc318b9drJDFlLjOEoiyEjgkQERLxUjP9eDFHCvKoTlPP6GyxzsPuB5C+3Kdr4ZXbSw1wRn+J3MYYn7zqUEcQSvcBQaIQ388= MR9hIPwxyGtrgkBLhp4ICEilVre5Qf5QL08KJJaO/ERu228eoSGLY/MLz/XlC7lxyPGHPz42Y8Qx9CjH8+M1A0jVooTseCKFJyMUXtOJQtb2bj84v75D5IBN/GrBTHIBYx5YNGvDhyIMrWRF84YEVhxYU8AEfhtS2xPCbbF9dnQ=